# Generated by Django 5.2.17 on 2026-09-08 20:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0011_counterpayout'),
        ('staff', '0004_staffrole_cashier_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed monthly base compensation in ₹', max_digits=12)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly')], default='monthly', max_length=20)),
                ('effective_from', models.DateField(blank=True, help_text='Date from which this salary structure became effective', null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=64)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=32)),
                ('upi_id', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profile', to='staff.staffmember')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_profiles', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Employee Salary Profile',
                'verbose_name_plural': 'Employee Salary Profiles',
                'ordering': ['employee__name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_number', models.CharField(db_index=True, help_text='Unique payroll voucher ID, e.g. SAL-202609-0001', max_length=64, unique=True)),
                ('month', models.PositiveSmallIntegerField(default=1, help_text='Calendar month of the salary period (1-12)')),
                ('year', models.PositiveIntegerField(default=2026, help_text='Calendar year of the salary period')),
                ('pay_period_label', models.CharField(blank=True, default='', help_text="Human-readable period label, e.g. 'September 2026'", max_length=64)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base monthly salary component in ₹', max_digits=12)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Performance bonuses, overtime, or festive incentives in ₹', max_digits=12)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deductions for counter advances, unpaid leaves, or penalties in ₹', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final net disbursed amount = base + bonus - deduction in ₹', max_digits=12)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='paid', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Direct Bank Transfer / NEFT'), ('upi', 'UPI / QR Scan'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=30)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Exact timestamp when the salary was disbursed')),
                ('paid_by_name', models.CharField(blank=True, default='', help_text='Name of the cashier / manager / owner who executed the disbursement', max_length=255)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Bank UTR #, Cheque #, or UPI Transaction Ref', max_length=100)),
                ('remarks', models.TextField(blank=True, default='', help_text='Notes regarding bonuses, deductions, or special adjustments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_disbursements', to='staff.staffmember')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_disbursements', to='staff.staffmember')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_disbursements', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Salary Disbursement',
                'verbose_name_plural': 'Salary Disbursements',
                'ordering': ['-paid_at', '-id'],
            },
        ),
    ]
