# Generated by Django 5.2.17 on 2026-09-09 09:44

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0012_dailyregistershift'),
        ('staff', '0004_staffrole_cashier_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(db_index=True, help_text='Unique expense voucher code, e.g. EXP-202609-0001', max_length=64, unique=True)),
                ('title', models.CharField(help_text='Short title or description of the operating expense', max_length=255)),
                ('category', models.CharField(choices=[('rent', 'Store Rent & Lease'), ('utilities', 'Electricity, Water & Utilities'), ('refreshments', 'Tea, Snacks & Daily Supplies'), ('repairs', 'Maintenance & Repairs'), ('logistics', 'Freight, Courier & Logistics'), ('marketing', 'Advertising & Marketing'), ('packaging', 'Packaging, Bags & Stationery'), ('cleaning', 'Housekeeping & Cleaning'), ('software', 'Software, POS & Subscriptions'), ('tax_legal', 'Taxes, Licenses & Legal'), ('other', 'Other Operating Expense')], db_index=True, default='other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expense amount in ₹', max_digits=12)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date the expense was incurred')),
                ('month', models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Calendar month (1-12)')),
                ('year', models.PositiveIntegerField(db_index=True, default=2026, help_text='Calendar year')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer / NEFT'), ('upi', 'UPI / QR Scan'), ('cheque', 'Cheque'), ('card', 'Debit / Credit Card'), ('other', 'Other')], default='cash', max_length=30)),
                ('paid_to', models.CharField(blank=True, default='', help_text='Vendor, landlord, service provider or payee name', max_length=255)),
                ('reference_number', models.CharField(blank=True, default='', help_text='Bill #, Invoice #, UTR #, or receipt reference', max_length=100)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional details, notes, or justification')),
                ('recorded_by_name', models.CharField(blank=True, default='', help_text='Name of the person who logged this expense', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_operating_expenses', to='staff.staffmember')),
                ('store', models.ForeignKey(blank=True, help_text='Store associated with this operational expense', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operating_expenses', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Operating Expense',
                'verbose_name_plural': 'Operating Expenses',
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
