# Generated by Django 5.2.17 on 2026-09-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_operatingexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarydisbursement',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salarydisbursement',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='salarydisbursement',
            name='store',
        ),
        migrations.DeleteModel(
            name='EmployeeSalaryProfile',
        ),
        migrations.DeleteModel(
            name='SalaryDisbursement',
        ),
    ]
