# Generated by Django 5.2.17 on 2026-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_salarydisbursement_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingexpense',
            name='category',
            field=models.CharField(choices=[('rent', 'Store Rent & Lease'), ('utilities', 'Electricity, Water & Utilities'), ('refreshments', 'Tea, Snacks & Daily Supplies'), ('repairs', 'Maintenance & Repairs'), ('logistics', 'Freight, Courier & Logistics'), ('marketing', 'Advertising & Marketing'), ('packaging', 'Packaging, Bags & Stationery'), ('cleaning', 'Housekeeping & Cleaning'), ('software', 'Software, POS & Subscriptions'), ('tax_legal', 'Taxes, Licenses & Legal'), ('salaries', 'Staff Salaries & Payroll'), ('other', 'Other Operating Expense')], db_index=True, default='other', max_length=50),
        ),
    ]
