# Generated by Django 5.2.17 on 2026-10-03 19:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_operatingexpense_category'),
        ('inventory', '0028_section_item_section'),
        ('staff', '0014_staffmember_inventory_scope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionMonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, default=2026, help_text='Calendar year (e.g. 2026)')),
                ('month', models.PositiveSmallIntegerField(db_index=True, default=10, help_text='Calendar month (1-12)')),
                ('target_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target monthly gross sales/revenue in ₹', max_digits=12)),
                ('target_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target monthly gross profit in ₹', max_digits=12)),
                ('actual_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frozen or computed actual gross revenue', max_digits=12)),
                ('actual_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frozen or computed actual gross profit', max_digits=12)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked permanently after the 3rd of subsequent month')),
                ('locked_at', models.DateTimeField(blank=True, help_text='Timestamp when goal was locked', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional performance notes or strategy from owner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_section_goals', to='staff.staffmember')),
                ('section', models.ForeignKey(help_text='Target store department/section', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to='inventory.section')),
                ('store', models.ForeignKey(blank=True, help_text='Store containing the section', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_monthly_goals', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Section Monthly Goal',
                'verbose_name_plural': 'Section Monthly Goals',
                'ordering': ['-year', '-month', 'section__name'],
                'unique_together': {('section', 'year', 'month')},
            },
        ),
    ]
