# Generated by Django 5.2.17 on 2026-09-08 11:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Wondersale Retail Inc.', max_length=255)),
                ('legal_entity_name', models.CharField(blank=True, default='Wondersale Retail Private Limited', max_length=255)),
                ('total_authorized_shares', models.PositiveIntegerField(default=1000000, help_text='Total authorized common shares available in company charter.')),
                ('current_share_price', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Current benchmark valuation price per share in Rupees.', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Equity Profile',
                'verbose_name_plural': 'Organization Equity Profiles',
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(choices=[('founder', 'Founder & Promoter'), ('co_founder', 'Co-Founder'), ('investor', 'Angel / VC Investor'), ('partner', 'Strategic Partner'), ('advisor', 'Board Advisor'), ('esop', 'ESOP Trust Pool'), ('director', 'Director / Executive')], db_index=True, default='investor', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('pan_or_tax_id', models.CharField(blank=True, default='', help_text='PAN, GSTIN, or Tax ID', max_length=50)),
                ('shares_count', models.PositiveIntegerField(default=0, help_text='Number of common shares held.')),
                ('price_per_share', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Weighted acquisition price per share.', max_digits=12)),
                ('total_investment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total capital invested by this stakeholder in Rupees.', max_digits=14)),
                ('equity_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Dynamically calculated ownership percentage of the company.', max_digits=6)),
                ('current_valuation_worth', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current monetary worth of this holding based on latest share price.', max_digits=14)),
                ('share_certificate_no', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active Shareholder'), ('exited', 'Exited / Bought Out'), ('dormant', 'Dormant')], db_index=True, default='active', max_length=20)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('voting_rights', models.BooleanField(default=True, help_text='Carries shareholder voting privileges.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'verbose_name_plural': 'Stakeholders',
                'ordering': ['-shares_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('initial_issuance', 'Initial Allotment / Issuance'), ('new_purchase', 'New Share Purchase / Round'), ('transfer', 'Share Transfer / Secondary Sale'), ('buyback', 'Company Buyback / Capital Reduction'), ('dilution_adjustment', 'Equity Dilution Event')], db_index=True, default='initial_issuance', max_length=30)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('price_per_share', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('resulting_equity_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('transaction_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('certificate_ref', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_transactions', to='stakeholders.stakeholder')),
            ],
            options={
                'verbose_name': 'Share Transaction',
                'verbose_name_plural': 'Share Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
