# Generated by Django 5.2.17 on 2026-09-08 12:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_customer_total_vip_savings_customer_vip_card_balance_and_more'),
        ('stakeholders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer / NEFT'), ('upi', 'UPI / QR'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=30)),
                ('reference_id', models.CharField(blank=True, default='', help_text='Bank UTR or Transaction reference number', max_length=100)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stakeholder Payout',
                'verbose_name_plural': 'Stakeholder Payouts',
                'ordering': ['-payout_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OrganizationProfile',
        ),
        migrations.AlterModelOptions(
            name='stakeholder',
            options={'ordering': ['-investment_amount', '-created_at'], 'verbose_name': 'Stakeholder', 'verbose_name_plural': 'Stakeholders'},
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='current_valuation_worth',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='equity_percentage',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='pan_or_tax_id',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='price_per_share',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='role',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='share_certificate_no',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='shares_count',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='total_investment',
        ),
        migrations.RemoveField(
            model_name='stakeholder',
            name='voting_rights',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='contract_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when agreement was signed'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Optional agreement expiration or renewal date', null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Capital invested into the organization in Rupees', max_digits=14),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Agreed contractual percentage share in net profit (e.g. 5.00 for 5%, 10.00 for 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Optional specific branch location, or null for organization-wide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholders', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='total_payout_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total profit disbursements paid up until today', max_digits=14),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Contract terms, bank account / UPI details, or notes'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='status',
            field=models.CharField(choices=[('active', 'Active Partner'), ('paused', 'Paused / On Hold'), ('settled', 'Contract Settled / Ended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='stakeholderpayout',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='stakeholders.stakeholder'),
        ),
        migrations.DeleteModel(
            name='ShareTransaction',
        ),
    ]
