# Generated by Django 5.2.17 on 2026-09-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, help_text='Unified product code & printed barcode value.', max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('quantity', models.IntegerField(default=0, help_text='Derived cached stock level calculated from StockMovement ledger.')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Purchase/cost price per unit.', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Retail selling price.', max_digits=12)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price. If null, treated as selling_price at read time.', max_digits=12, null=True)),
                ('location_section', models.CharField(blank=True, default='', help_text='Aisle, shelf, or store section location.', max_length=100)),
                ('expiry_date', models.DateField(blank=True, help_text='Product expiration date if applicable.', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams.', max_digits=10, null=True)),
                ('source', models.CharField(choices=[('new', 'New System Item'), ('legacy', 'Legacy System Import')], db_index=True, default='new', max_length=20)),
                ('legacy_uid', models.CharField(blank=True, help_text='Original code from legacy system if different from UID.', max_length=64, null=True)),
                ('needs_new_barcode_printed', models.BooleanField(db_index=True, default=False, help_text='Flag indicating staff need to print & affix a fresh barcode label.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='items', to='inventory.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Item Image',
                'verbose_name_plural': 'Item Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField(help_text='Positive for stock addition, negative for stock reduction.')),
                ('reason', models.CharField(choices=[('initial_import', 'Initial Import'), ('manual_adjustment', 'Manual Adjustment'), ('restock', 'Restock'), ('damage', 'Damaged / Discarded Stock'), ('return', 'Customer / Supplier Return'), ('audit_correction', 'Inventory Audit Correction')], default='manual_adjustment', max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
