# Generated by Django 5.2.17 on 2026-09-05 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_categories_category_description_and_more'),
        ('staff', '0003_alter_staffrole_can_access_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
