# Generated by Django 5.2.17 on 2026-09-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_performed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='allow_manual_uid',
            field=models.BooleanField(default=False, help_text='Allow manual editing/entry of UIDs when adding items for this store.'),
        ),
    ]
