# Generated by Django 5.2.17 on 2026-09-06 19:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_store_allow_manual_uid'),
        ('staff', '0003_alter_staffrole_can_access_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('total_purchases_count', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('initial_import', 'Initial Import'), ('manual_adjustment', 'Manual Adjustment'), ('restock', 'Restock'), ('damage', 'Damaged / Discarded Stock'), ('return', 'Customer / Supplier Return'), ('audit_correction', 'Inventory Audit Correction'), ('sale', 'POS Customer Sale')], default='manual_adjustment', max_length=50),
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Unique invoice reference number, e.g. INV-2026-00001.', max_length=64, unique=True)),
                ('customer_phone', models.CharField(db_index=True, max_length=30)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('cashier_name', models.CharField(blank=True, default='', max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Debit / Credit Card'), ('upi', 'UPI / QR Code'), ('other', 'Other')], default='cash', max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('change_returned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_processed', to='staff.staffmember')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to='inventory.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Sale Order',
                'verbose_name_plural': 'Sale Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_uid', models.CharField(max_length=64)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='inventory.item')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.saleorder')),
            ],
            options={
                'verbose_name': 'Sale Order Item',
                'verbose_name_plural': 'Sale Order Items',
                'ordering': ['id'],
            },
        ),
    ]
