# Generated by Django 5.2.17 on 2026-09-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_customer_alter_stockmovement_reason_saleorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / QR Code'), ('vip_card', 'VIP Card'), ('card', 'Debit / Credit Card'), ('other', 'Other')], default='cash', max_length=50),
        ),
    ]
