# Generated by Django 5.2.17 on 2026-09-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_saleorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='gst_number',
            field=models.CharField(blank=True, default='', help_text='GSTIN / GST Tax Registration number for this branch (e.g. 23ANGPK5446D2Z8).', max_length=50),
        ),
    ]
