# Generated by Django 5.2.17 on 2026-09-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_store_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store / Branch location where this customer is registered or primarily belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='inventory.store'),
        ),
    ]
