# Generated by Django 5.2.17 on 2026-09-07 19:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_customer_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_vip_savings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative discount savings earned by customer via VIP Card.', max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='vip_card_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Active VIP card credit balance in Rupees (1 Credit = 1 Rupee).', max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='vip_card_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vip_card_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='vip_card_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Unique RFID Card UID assigned to this customer.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='vip_card_uid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='vip_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='cashier_name',
            field=models.CharField(blank=True, default='Cashier', max_length=255),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='customer_phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_orders', to='inventory.store'),
        ),
        migrations.CreateModel(
            name='VIPCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uid', models.CharField(db_index=True, max_length=100)),
                ('transaction_type', models.CharField(choices=[('issue', 'Card Issue & Initial Credit'), ('recharge', 'Balance Top-up / Recharge'), ('debit', 'Sale Payment Debit'), ('refund', 'Refund / Reversal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_transactions', to='inventory.customer')),
                ('sale_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_transactions', to='inventory.saleorder')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_transactions', to='inventory.store')),
            ],
            options={
                'verbose_name': 'VIP Card Transaction',
                'verbose_name_plural': 'VIP Card Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
