# Generated by Django 5.2.17 on 2026-09-08 16:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_customer_total_vip_savings_customer_vip_card_balance_and_more'),
        ('staff', '0004_staffrole_cashier_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_number', models.CharField(db_index=True, help_text='Sequential reference number, e.g. PAY-20260908-0001.', max_length=64, unique=True)),
                ('paid_by_name', models.CharField(default='Cashier', max_length=255)),
                ('paid_to', models.CharField(help_text='Name of the person / vendor / driver to whom the payment was made.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / Online QR'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer / NEFT'), ('other', 'Other')], default='cash', max_length=50)),
                ('category', models.CharField(choices=[('stock_purchase', 'Stock Delivery / Purchase'), ('freight_delivery', 'Freight & Courier / Transport'), ('store_maintenance', 'Store Repairs & Maintenance'), ('daily_expense', 'Tea & Daily Supplies / Refreshments'), ('utility_bill', 'Electricity / Internet / Utilities'), ('other', 'Other Counter Expense')], default='stock_purchase', max_length=50)),
                ('reason', models.TextField(blank=True, default='', help_text='Detailed purpose / reason for this counter payout.')),
                ('receipt_number', models.CharField(blank=True, default='', help_text='Supplier invoice, bill, LR, or voucher number.', max_length=100)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the payment occurred.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_recorded', to='staff.staffmember')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_payouts', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Counter Payout',
                'verbose_name_plural': 'Counter Payouts',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
    ]
