# Generated by Django 5.2.17 on 2026-09-08 20:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_counterpayout'),
        ('staff', '0004_staffrole_cashier_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRegisterShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.CharField(db_index=True, help_text='Sequential register shift reference number, e.g. REG-20260909-0001.', max_length=64, unique=True)),
                ('cashier_name', models.CharField(default='Cashier', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open / In Progress'), ('closed', 'Closed / Reconciled')], db_index=True, default='open', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Exact timestamp when the register shift was opened for the day')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Starting physical cash float in drawer when opening counter (₹)', max_digits=12)),
                ('opening_notes', models.TextField(blank=True, default='', help_text='Notes / denomination breakdown on Day-Start')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Exact timestamp when the register shift was closed for the day', null=True)),
                ('closing_cash_counted', models.DecimalField(blank=True, decimal_places=2, help_text='Actual physical cash counted in drawer at Day-End (₹)', max_digits=12, null=True)),
                ('cash_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total customer cash sales recorded during this shift', max_digits=12)),
                ('cash_payouts_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cash counter payouts deducted during this shift', max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected drawer total = opening_cash + cash_sales - cash_payouts', max_digits=12)),
                ('cash_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discrepancy amount = closing_cash_counted - expected_cash (0 = match, + = over, - = short)', max_digits=12)),
                ('closing_notes', models.TextField(blank=True, default='', help_text='Notes / reason for any cash discrepancy on Day-End')),
                ('closed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_shifts_opened', to='staff.staffmember')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_shifts_closed', to='staff.staffmember')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_shifts', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Daily Register Shift',
                'verbose_name_plural': 'Daily Register Shifts',
                'ordering': ['-opened_at', '-id'],
            },
        ),
    ]
