# Generated by Django 5.2.17 on 2026-09-10 11:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_dailyregistershift'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='split_cash_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash portion paid in split payment (₹)', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='split_upi_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='UPI portion paid in split payment (₹)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / QR Code'), ('vip_card', 'VIP Card'), ('card', 'Debit / Credit Card'), ('split', 'Split Payment (Cash + UPI)'), ('other', 'Other')], default='cash', max_length=50),
        ),
    ]
