# Generated by Django 5.2.17 on 2026-09-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_saleorder_split_cash_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='return_reference',
            field=models.CharField(blank=True, default='', help_text='Original invoice number if this order is a return/credit note.', max_length=64),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total units of this line item returned across return transactions.'),
        ),
        migrations.AlterField(
            model_name='counterpayout',
            name='category',
            field=models.CharField(choices=[('stock_purchase', 'Stock Delivery / Purchase'), ('freight_delivery', 'Freight & Courier / Transport'), ('store_maintenance', 'Store Repairs & Maintenance'), ('daily_expense', 'Tea & Daily Supplies / Refreshments'), ('utility_bill', 'Electricity / Internet / Utilities'), ('customer_refund', 'Customer Return / Bill Refund'), ('other', 'Other Counter Expense')], default='stock_purchase', max_length=50),
        ),
    ]
