# Generated by Django 5.2.17 on 2026-09-13 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_saleorder_return_reference_and_more'),
        ('staff', '0004_staffrole_cashier_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Recorded purchase/cost price per unit.', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Recorded retail selling price.', max_digits=12)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, help_text='Recorded Maximum Retail Price.', max_digits=12, null=True)),
                ('reason', models.CharField(default='Initial Stocking', help_text='Reason for price recording/change (e.g. Initial Stocking, Price Adjustment, Restock Batch).', max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('performed_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.item')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Item Price History',
                'verbose_name_plural': 'Item Price Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
