# Generated by Django 5.2.17 on 2026-09-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_itempricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='primary_subcategory',
            field=models.ForeignKey(blank=True, help_text='Primary financial anchor used for 100% consistent, single-category P&L attribution and pie charts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_items', to='inventory.subcategory'),
        ),
    ]
