# Generated by Django 5.2.17 on 2026-09-17 15:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_backfill_primary_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='enable_gst',
            field=models.BooleanField(default=True, help_text='Enable or disable GST deduction across financial reports'),
        ),
        migrations.AddField(
            model_name='store',
            name='gst_calculation_mode',
            field=models.CharField(choices=[('all', 'All Revenue (Cash + UPI)'), ('upi_only', 'UPI Payments Only')], default='all', help_text='Calculate GST on total gross sales or restrict to UPI payments only', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST Tax Rate percentage (e.g. 18.00%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='vipcardtransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI')], default='cash', help_text='Payment method used for card recharge or initial issue', max_length=20),
        ),
    ]
