# Generated by Django 5.2.17 on 2026-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_store_enable_gst_store_gst_calculation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional product description and specifications.'),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in cm.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width in cm.', max_digits=10, null=True),
        ),
    ]
