# Generated by Django 5.2.17 on 2026-09-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_supplier_item_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text='IANA Timezone for store operations (e.g. Asia/Kolkata)', max_length=64),
        ),
    ]
