# Generated by Django 5.2.17 on 2026-09-20 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_store_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ai_description_draft',
            field=models.TextField(blank=True, default='', help_text='Generated AI description draft pending manager review & approval.'),
        ),
        migrations.AddField(
            model_name='item',
            name='ai_description_error',
            field=models.TextField(blank=True, default='', help_text='Error message or skipping reason if generation failed.'),
        ),
        migrations.AddField(
            model_name='item',
            name='ai_description_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending Generation'), ('generating', 'Generating in Background'), ('ready', 'Ready for Review'), ('failed', 'Generation Failed'), ('skipped_no_image', 'Skipped (No Image)'), ('applied', 'Applied to Description')], db_index=True, default='none', help_text='Current lifecycle status of AI generated description.', max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='ai_description_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when AI description was last generated or updated.', null=True),
        ),
        migrations.CreateModel(
            name='AIDescriptionBatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='running', max_length=30)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.PositiveIntegerField(default=0)),
                ('item_ids', models.JSONField(default=list, help_text='List of Item PKs included in this generation batch.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_description_jobs', to='inventory.store')),
            ],
            options={
                'verbose_name': 'AI Description Batch Job',
                'verbose_name_plural': 'AI Description Batch Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
