# Generated by Django 5.2.17 on 2026-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_item_ai_description_draft_item_ai_description_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidescriptionbatchjob',
            name='status_message',
            field=models.CharField(blank=True, default='', help_text='Real-time pause / quota status note (e.g. Rate limit paused, Daily limit reached).', max_length=255),
        ),
    ]
