# Generated by Django 5.2.17 on 2026-10-01 08:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_counterpayout_employee_staff_payout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='enable_stakeholders',
            field=models.BooleanField(default=True, help_text='Enable or disable the Stakeholders profit-sharing module and calculations'),
        ),
        migrations.AlterField(
            model_name='dailyregistershift',
            name='post_close_payouts_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cash paid out after this shift was formally closed (e.g. manager paid staff wages from closed drawer). Deducted from net handover.', max_digits=12),
        ),
    ]
