# Generated by Django 5.2.17 on 2026-10-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_store_enable_stakeholders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_master_variant',
            field=models.BooleanField(default=False, help_text='Indicates whether this was the original anchor item when the variant family was created.'),
        ),
        migrations.AddField(
            model_name='item',
            name='variant_group_id',
            field=models.CharField(blank=True, db_index=True, help_text='UUID string grouping sibling product variants and batches together.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='variant_name',
            field=models.CharField(blank=True, default='', help_text="Human-friendly variant tag (e.g. 'Batch Exp Nov 2026', 'Vendor ABC', 'Red / L').", max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('initial_import', 'Initial Import'), ('manual_adjustment', 'Manual Adjustment'), ('restock', 'Restock'), ('damage', 'Damaged / Discarded Stock'), ('return', 'Customer / Supplier Return'), ('audit_correction', 'Inventory Audit Correction'), ('sale', 'POS Customer Sale'), ('expired', 'Expired Stock Write-Off')], default='manual_adjustment', max_length=50),
        ),
    ]
