# Generated by Django 5.2.17 on 2026-10-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_variant_group_and_expired_reason'),
        ('staff', '0010_interim_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyregistershift',
            name='is_discrepancy_settled',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this shift discrepancy has been verified, settled, or cleared'),
        ),
        migrations.AddField(
            model_name='dailyregistershift',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when discrepancy was settled or cleared', null=True),
        ),
        migrations.AddField(
            model_name='dailyregistershift',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_shifts_settled', to='staff.staffmember'),
        ),
        migrations.AddField(
            model_name='dailyregistershift',
            name='settled_by_name',
            field=models.CharField(blank=True, default='', help_text='Name of manager or admin who settled/cleared the discrepancy', max_length=255),
        ),
        migrations.AddField(
            model_name='dailyregistershift',
            name='settlement_action',
            field=models.CharField(blank=True, default='', help_text='Action taken (e.g. approved_loss, recovered_from_cashier, reconciled_counting_error, surplus_deposited, waived, other)', max_length=50),
        ),
        migrations.AddField(
            model_name='dailyregistershift',
            name='settlement_notes',
            field=models.TextField(blank=True, default='', help_text='Audit notes explaining verification and settlement/clearance'),
        ),
    ]
