# Generated by Django 5.2.17 on 2026-10-03 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_dailyregistershift_is_discrepancy_settled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, default='', help_text='Short code / aisle identifier (e.g. SEC-01, MENS, FL-1).', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='#3B82F6', help_text='Hex color code for badges & charts.', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, help_text='Optional specific store attribution. If null, available across all stores.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Store section / department / aisle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.section'),
        ),
    ]
