# Generated by Django 5.2.17 on 2026-10-03 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_section_item_section'),
        ('staff', '0014_staffmember_inventory_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Optional photo evidence for damaged, expired, or broken stock write-offs.', null=True, upload_to='broken_proofs/'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('initial_import', 'Initial Import'), ('manual_adjustment', 'Manual Adjustment'), ('restock', 'Restock'), ('damage', 'Damaged / Discarded Stock'), ('return', 'Customer / Supplier Return'), ('audit_correction', 'Inventory Audit Correction'), ('sale', 'POS Customer Sale'), ('expired', 'Expired Stock Write-Off'), ('broken', 'Broken / Damaged Write-Off')], default='manual_adjustment', max_length=50),
        ),
        migrations.CreateModel(
            name='BrokenItemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Units of physical merchandise broken or damaged.')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost price per unit at the time of write-off.', max_digits=12)),
                ('total_loss', models.DecimalField(decimal_places=2, help_text='Total financial loss = quantity * cost_price.', max_digits=12)),
                ('reason', models.TextField(help_text='Mandatory explanation or write-off note describing how the damage occurred.')),
                ('proof_image', models.ImageField(help_text='Mandatory visual photo evidence of broken merchandise.', upload_to='broken_proofs/')),
                ('reported_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broken_reports', to='inventory.item')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_broken_items', to='staff.staffmember')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broken_reports', to='inventory.section')),
                ('stock_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broken_report', to='inventory.stockmovement')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broken_reports', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Broken Item Report',
                'verbose_name_plural': 'Broken Item Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
