# Generated by Django 5.2.17 on 2026-10-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_stockmovement_proof_image_alter_stockmovement_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('current_value', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Sequence',
                'verbose_name_plural': 'Global Sequences',
            },
        ),
    ]
