# Generated by Django 5.2.17 on 2026-10-07 15:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_globalsequence'),
        ('staff', '0014_staffmember_inventory_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining balance owed by customer (total_amount - amount_paid)', max_digits=12),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='initial_payment_method',
            field=models.CharField(blank=True, default='', help_text='Method used for initial payment when partial checkout occurs (cash, upi, card)', max_length=50),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='is_fully_paid',
            field=models.BooleanField(db_index=True, default=True, help_text='True if order balance_due <= 0.00, False if pending dues exist'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sum of all payments received so far (₹)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / QR Code'), ('vip_card', 'VIP Card'), ('card', 'Debit / Credit Card'), ('split', 'Split Payment (Cash + UPI)'), ('partial', 'Partial Payment (Due / Khata)'), ('other', 'Other')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partially Paid (Due)'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount received in this payment transaction (₹)', max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / QR Code'), ('card', 'Debit / Credit Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=50)),
                ('collected_by_name', models.CharField(blank=True, default='Staff', max_length=255)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dues_collected', to='staff.staffmember')),
                ('order', models.ForeignKey(help_text='The sale order / invoice this payment applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.saleorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payments', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Order Payment Transaction',
                'verbose_name_plural': 'Order Payment Transactions',
                'ordering': ['created_at'],
            },
        ),
    ]
