# Generated by Django 5.2.17 on 2026-10-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_saleorder_balance_due_and_more'),
        ('staff', '0014_staffmember_inventory_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenitemreport',
            name='fine_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Amount fined to the employee for this incident.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='brokenitemreport',
            name='fine_ledger_entry',
            field=models.ForeignKey(blank=True, help_text='Linked staff ledger entry debiting the fine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broken_reports', to='staff.employeeledgerentry'),
        ),
        migrations.AddField(
            model_name='brokenitemreport',
            name='fined_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the fine was levied.', null=True),
        ),
        migrations.AddField(
            model_name='brokenitemreport',
            name='fined_employee',
            field=models.ForeignKey(blank=True, help_text='Employee fined for the damaged goods write-off.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broken_fines', to='staff.employee'),
        ),
        migrations.AddField(
            model_name='brokenitemreport',
            name='is_fined',
            field=models.BooleanField(default=False, help_text='Flag indicating whether an employee was fined for this write-off.'),
        ),
    ]
