# Generated by Django 5.2.17 on 2026-10-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_brokenitemreport_fine_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenitemreport',
            name='is_waived',
            field=models.BooleanField(default=False, help_text='Flag indicating management decided not to fine any employee (absorbed 100% as store loss).'),
        ),
        migrations.AddField(
            model_name='brokenitemreport',
            name='waived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when fine was waived / accepted as store loss.', null=True),
        ),
        migrations.AddField(
            model_name='brokenitemreport',
            name='waived_by',
            field=models.CharField(blank=True, default='', help_text='Staff or manager who decided not to fine.', max_length=255),
        ),
    ]
