# Generated by Django 5.2.17 on 2026-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_brokenitemreport_is_waived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_listed_on_website',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this item is published/listed on the online website.'),
        ),
    ]
