# Generated by Django 5.2.17 on 2026-10-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_item_is_listed_on_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='legacy_uid',
            field=models.CharField(blank=True, db_index=True, help_text='Original code from legacy system if different from UID.', max_length=64, null=True),
        ),
    ]
