# Generated by Django 5.2.17 on 2026-09-04 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_owner', models.BooleanField(default=False, help_text='Designates the account as an Owner with complete system privileges.')),
                ('can_access_inventory', models.BooleanField(default=True, help_text='Permission to view inventory and scan products.')),
                ('can_adjust_stock', models.BooleanField(default=False, help_text='Permission to perform manual additions and deductions on stock.')),
                ('can_access_billing', models.BooleanField(default=False, help_text='Permission to access billing/POS module (Phase 2).')),
                ('can_access_staff', models.BooleanField(default=False, help_text='Permission to view staff members and configure roles (Owner privilege).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(db_index=True, help_text='Staff login ID (e.g. OWNER01, CASHIER01, admin).', max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this staff member can log in.')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='inventory.store')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='staff.staffrole')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['name'],
            },
        ),
    ]
