# Generated by Django 5.2.17 on 2026-09-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='allowed_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of menu button module IDs this role can see and access.'),
        ),
    ]
