# Generated by Django 5.2.17 on 2026-09-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffrole_allowed_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrole',
            name='can_access_inventory',
            field=models.BooleanField(default=False, help_text='Permission to view inventory and scan products.'),
        ),
    ]
