# Generated by Django 5.2.17 on 2026-09-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffrole_can_access_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='cashier_role',
            field=models.CharField(blank=True, choices=[('cashier', 'Cashier'), ('head_cashier', 'Head Cashier')], default='cashier', help_text="Designation tier when billing & pos is accessible ('cashier' vs 'head_cashier').", max_length=50),
        ),
    ]
