# Generated by Django 5.2.17 on 2026-09-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffrole_cashier_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Assigned section/department in store (optional, e.g. Menswear, Electronics; can be left blank).', max_length=128),
        ),
    ]
