# Generated by Django 5.2.17 on 2026-09-19 12:54

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_store_timezone'),
        ('staff', '0006_leavetype_attendanceday_attendancesession_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='staff_member',
            field=models.OneToOneField(blank=True, help_text='Associated staff login user account if linked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='staff.staffmember'),
        ),
        migrations.CreateModel(
            name='FinanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('salary_expense_accrued', 'Salary Expense Accrued'), ('salary_payout_recorded', 'Salary Payout Recorded'), ('advance_recorded', 'Advance Recorded'), ('salary_reversed', 'Salary Reversed')], db_index=True, max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_ref', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('consumed', 'Consumed')], default='consumed', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_events', to='staff.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_events', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Finance Event',
                'verbose_name_plural': 'Finance Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Bonus'), ('fine', 'Fine / Penalty'), ('incentive', 'Incentive'), ('advance_recovery', 'Advance Recovery'), ('other', 'Other Adjustment')], default='bonus', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('label', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffmember')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='staff.employee')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Payroll Adjustment',
                'verbose_name_plural': 'Payroll Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], db_index=True, default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, default='')),
                ('rules_snapshot', models.JSONField(blank=True, default=dict)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_payrolls', to='staff.staffmember')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_payrolls', to='staff.staffmember')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='inventory.store')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-year', '-month'],
                'unique_together': {('store', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='MONTHLY', max_length=20)),
                ('gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_additions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('days_summary', models.JSONField(blank=True, default=dict, help_text='Snapshot of days: present, half, absent, paid_leave, unpaid_leave, offs, holidays, late_count.')),
                ('rules_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_included', models.BooleanField(default=True, help_text='Flag whether this employee is included in final payout disbursement.')),
                ('exclusion_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_statements', to='staff.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='staff.payrollrun')),
            ],
            options={
                'verbose_name': 'Salary Statement',
                'verbose_name_plural': 'Salary Statements',
                'ordering': ['employee__employee_code'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='SalaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('addition', 'Addition')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('formula_text', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, default='', max_length=100)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='staff.salarystatement')),
            ],
            options={
                'verbose_name': 'Salary Line',
                'verbose_name_plural': 'Salary Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('entry_type', models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('SALARY_ACCRUAL', 'Salary Accrual'), ('PAYOUT', 'Salary Payout'), ('ADVANCE', 'Advance Paid'), ('BONUS', 'Bonus'), ('FINE', 'Fine'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive = store owes staff; negative = staff owes store.', max_digits=12)),
                ('payment_method', models.CharField(blank=True, default='cash', max_length=30)),
                ('reference_no', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffmember')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='staff.employee')),
                ('reversed_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='staff.employeeledgerentry')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_ledger_entries', to='inventory.store')),
                ('related_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='staff.salarystatement')),
            ],
            options={
                'verbose_name': 'Employee Ledger Entry',
                'verbose_name_plural': 'Employee Ledger Entries',
                'ordering': ['entry_date', 'id'],
                'indexes': [models.Index(fields=['employee', 'entry_date'], name='staff_emplo_employe_65575c_idx'), models.Index(fields=['store', 'entry_date'], name='staff_emplo_store_i_33692c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('MONTHLY', 'Monthly Salary'), ('DAILY', 'Daily Wage')], db_index=True, default='MONTHLY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monthly salary or Daily wage rate in ₹.', max_digits=12)),
                ('overtime_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly overtime compensation rate in ₹ (null = calculate from base / multiplier).', max_digits=12, null=True)),
                ('from_date', models.DateField(db_index=True, help_text='Effective start date (inclusive).')),
                ('to_date', models.DateField(blank=True, db_index=True, help_text='Effective end date (null = indefinitely active).', null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='staff.employee')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['-from_date'],
                'indexes': [models.Index(fields=['employee', 'from_date'], name='staff_salar_employe_807ff7_idx')],
            },
        ),
    ]
