# Generated by Django 5.2.17 on 2026-09-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_employee_staff_member_financeevent_payrolladjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Contact phone number.', max_length=30),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='photo',
            field=models.ImageField(blank=True, help_text='Staff profile photograph.', null=True, upload_to='staff/photos/'),
        ),
    ]
