# Generated by Django 5.2.17 on 2026-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_staffmember_phone_staffmember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='session_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Active session token. Rotated on password change or explicit revocation to invalidate old device sessions.', max_length=64),
        ),
    ]
