# Generated by Django 5.2.17 on 2026-10-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_staffmember_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', help_text='Optional reason / note from the employee.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_password_requests', to='staff.staffmember')),
                ('staff_member', models.ForeignKey(help_text='Staff member who raised the request.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Password Reset Request',
                'verbose_name_plural': 'Staff Password Reset Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
