# Generated by Django 5.2.17 on 2026-10-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_section_item_section'),
        ('staff', '0012_phase1_password_reset_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('deadline', models.DateTimeField(help_text='Target completion deadline.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Verification'), ('verified', 'Verified & Closed'), ('revision_needed', 'Revision Needed')], db_index=True, default='pending', max_length=25)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('proof_image', models.ImageField(blank=True, help_text='Mandatory photographic proof of completed task.', null=True, upload_to='task_proofs/')),
                ('write_off_notes', models.TextField(blank=True, default='', help_text='Mandatory notes provided by employee upon submitting proof.')),
                ('revision_notes', models.TextField(blank=True, default='', help_text='Notes/feedback provided by admin if revision is requested.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_on_time', models.BooleanField(default=True, help_text='Whether submission was on or before the deadline.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Staff member assigned to complete this task.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='staff.staffmember')),
                ('created_by', models.ForeignKey(help_text='Admin / Owner who created and assigned the task.', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='staff.staffmember')),
                ('section', models.ForeignKey(blank=True, help_text='Optional section department bound to this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_tasks', to='inventory.section')),
                ('store', models.ForeignKey(help_text='Store location for this task.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_tasks', to='inventory.store')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who approved/verified this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tasks', to='staff.staffmember')),
            ],
            options={
                'verbose_name': 'Employee Task',
                'verbose_name_plural': 'Employee Tasks',
                'ordering': ['deadline', '-priority', '-created_at'],
            },
        ),
    ]
