# Generated by Django 5.2.17 on 2026-10-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_employeetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='inventory_scope',
            field=models.CharField(blank=True, choices=[('full', 'Full Store Inventory'), ('assigned_section', 'Assigned Section Only')], default='full', help_text='Optional inventory scope override for this staff member (defaults to role scope if left blank).', max_length=30),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='inventory_scope',
            field=models.CharField(blank=True, choices=[('full', 'Full Store Inventory'), ('assigned_section', 'Assigned Section Only')], default='full', help_text="Access scope when inventory module is enabled ('full' store vs 'assigned_section' only).", max_length=30),
        ),
    ]
